Aws school slides update
sfeir-open-source/sfeir-school-terraform pull request #253
Opened 2024-11-25 10:03 UTC by cdarcy

- Add speakers
- Add specific aws
- Fix out of screen slides

2024-11-25 11:12 UTC, Tibeno88 requested changes

2024-11-25 11:12 UTC, Tibeno88 commented on docs/assets/images/speakers/bma.jpg
Change avec cette image https://github.com/sfeir-open-source/polytech-microservice/blob/main/docs/assets/images/bm.jpg

2024-11-25 11:12 UTC, Tibeno88 commented on docs/markdown/00-school/planning.md
> +
C'est quoi la différence avec la prez GCP

2024-11-28 08:58 UTC, cdarcy commented on docs/assets/images/speakers/bma.jpg
done

2024-11-28 08:58 UTC, cdarcy commented on docs/markdown/00-school/planning.md
> +
done

2024-11-28 12:40 UTC, Tibeno88 approved these changes

2024-12-05 08:24 UTC, merged